/**
 * Department-level operational KPIs — best practice metrics for each
 * department type in a professional services organization.
 *
 * These are SEPARATE from the 8 maturity dimensions. They measure
 * how well the department is performing its core function, with
 * industry benchmarks for context.
 *
 * Sources: SPI Research (403 PS firms), TSIA, Gartner, SHRM,
 * APQC, Forrester, and USDM FY2025 department review findings.
 */

export interface DeptKPI {
  name: string
  description: string
  unit: string // '%', 'days', '$', 'ratio', 'score', 'count'
  benchmark_low: string   // Below average / needs improvement
  benchmark_mid: string   // Average / acceptable
  benchmark_high: string  // Top quartile / best in class
  source: string          // Where the benchmark comes from
  why_it_matters: string
}

export type DeptKPISet = {
  department_type: string
  intro: string
  kpis: DeptKPI[]
}

export const DEPT_KPIS: Record<string, DeptKPISet> = {
  Delivery: {
    department_type: 'Delivery',
    intro: 'Delivery is the revenue engine. These KPIs measure whether the department is billing efficiently, delivering quality, and managing capacity to maximize margin.',
    kpis: [
      {
        name: 'Billable Utilization Rate',
        description: 'Percentage of available hours billed to clients.',
        unit: '%',
        benchmark_low: '<65%',
        benchmark_mid: '65-75%',
        benchmark_high: '>75%',
        source: 'SPI Research PS Benchmark (median 71%)',
        why_it_matters: 'The single most important lever for PS profitability. Each 1% improvement translates to ~$442K revenue at USDM scale.',
      },
      {
        name: 'Project Gross Margin',
        description: 'Revenue minus direct labor cost per engagement.',
        unit: '%',
        benchmark_low: '<30%',
        benchmark_mid: '30-40%',
        benchmark_high: '>40%',
        source: 'SPI Research (median 36% for PS firms)',
        why_it_matters: 'Measures pricing power and delivery efficiency. USDM FY2025: 37.7% gross margin overall.',
      },
      {
        name: 'On-Time Project Delivery',
        description: 'Percentage of projects completed within original timeline.',
        unit: '%',
        benchmark_low: '<70%',
        benchmark_mid: '70-85%',
        benchmark_high: '>85%',
        source: 'TSIA Professional Services benchmark',
        why_it_matters: 'Late delivery erodes margin (extra hours) and damages client relationships / renewal rates.',
      },
      {
        name: 'Revenue per Consultant',
        description: 'Annual revenue generated per billable consultant.',
        unit: '$',
        benchmark_low: '<$150K',
        benchmark_mid: '$150K-$220K',
        benchmark_high: '>$220K',
        source: 'SPI Research (median $198K)',
        why_it_matters: 'Combines utilization and rate realization into a single productivity metric.',
      },
      {
        name: 'Consultant Retention Rate',
        description: 'Annual retention of billable delivery staff.',
        unit: '%',
        benchmark_low: '<80%',
        benchmark_mid: '80-90%',
        benchmark_high: '>90%',
        source: 'SPI Research (median 85%)',
        why_it_matters: 'Losing consultants means lost revenue, client disruption, and recruiting cost ($15-25K per replacement).',
      },
      {
        name: 'Bench Time',
        description: 'Average days between client engagements per consultant.',
        unit: 'days',
        benchmark_low: '>20 days',
        benchmark_mid: '10-20 days',
        benchmark_high: '<10 days',
        source: 'SPI Research',
        why_it_matters: 'Bench time is pure cost with zero revenue. Directly reduces utilization and margin.',
      },
      {
        name: 'Client Satisfaction Score',
        description: 'Average client satisfaction rating on project delivery.',
        unit: 'score',
        benchmark_low: '<7.0 / 10',
        benchmark_mid: '7.0-8.5',
        benchmark_high: '>8.5 / 10',
        source: 'TSIA (top quartile >8.5)',
        why_it_matters: 'Client satisfaction drives renewals, referrals, and expansion revenue. Leading indicator of growth.',
      },
      {
        name: 'Effective Bill Rate Realization',
        description: 'Actual billed rate as percentage of standard rate (after discounts, write-offs).',
        unit: '%',
        benchmark_low: '<85%',
        benchmark_mid: '85-95%',
        benchmark_high: '>95%',
        source: 'SPI Research',
        why_it_matters: 'Measures pricing discipline. Low realization signals excessive discounting or scope creep.',
      },
      {
        name: 'Contractor Leverage Ratio',
        description: 'Percentage of delivery hours from contractors (1099/C2C) vs W2 employees.',
        unit: '%',
        benchmark_low: '<20% (under-leveraged)',
        benchmark_mid: '20-40%',
        benchmark_high: '40-60% (margin-optimized)',
        source: 'USDM FY2025 analysis (+21.3% margin/head for contractors)',
        why_it_matters: 'Contractors provide margin uplift and workforce flexibility. Over-leverage creates quality/IP risk.',
      },
      {
        name: 'SOW Change Order Rate',
        description: 'Percentage of projects requiring scope changes.',
        unit: '%',
        benchmark_low: '>30% (poor scoping)',
        benchmark_mid: '15-30%',
        benchmark_high: '<15%',
        source: 'Industry standard',
        why_it_matters: 'High change order rates signal poor scoping, which causes client friction and margin leakage.',
      },
    ],
  },

  'Sales/Growth': {
    department_type: 'Sales/Growth',
    intro: 'Sales drives top-line growth. These KPIs measure pipeline health, conversion efficiency, and the cost of acquiring new business.',
    kpis: [
      {
        name: 'Pipeline Coverage Ratio',
        description: 'Total qualified pipeline value divided by quota/target.',
        unit: 'ratio',
        benchmark_low: '<2x',
        benchmark_mid: '2x-3x',
        benchmark_high: '>3x',
        source: 'Forrester / SBI (best practice 3x)',
        why_it_matters: 'Insufficient pipeline coverage means missed targets. 3x coverage accounts for typical PS win rates.',
      },
      {
        name: 'Win Rate',
        description: 'Percentage of qualified opportunities that close-won.',
        unit: '%',
        benchmark_low: '<20%',
        benchmark_mid: '20-35%',
        benchmark_high: '>35%',
        source: 'SPI Research (median 28% for PS firms)',
        why_it_matters: 'Low win rate wastes sales capacity and indicates positioning or qualification problems.',
      },
      {
        name: 'Sales Cycle Length',
        description: 'Average days from opportunity creation to close.',
        unit: 'days',
        benchmark_low: '>120 days',
        benchmark_mid: '60-120 days',
        benchmark_high: '<60 days',
        source: 'SPI Research (median 84 days for PS)',
        why_it_matters: 'Long cycles tie up resources and delay revenue recognition. Life sciences sales cycles tend to be longer.',
      },
      {
        name: 'Revenue per Sales Rep',
        description: 'Annual revenue closed per quota-carrying rep.',
        unit: '$',
        benchmark_low: '<$1M',
        benchmark_mid: '$1M-$2M',
        benchmark_high: '>$2M',
        source: 'SPI Research (varies by PS segment)',
        why_it_matters: 'Measures sales productivity. Low revenue per rep suggests territory, enablement, or market fit issues.',
      },
      {
        name: 'New Logo Revenue %',
        description: 'Percentage of revenue from new clients vs existing.',
        unit: '%',
        benchmark_low: '<15%',
        benchmark_mid: '15-30%',
        benchmark_high: '30-40%',
        source: 'TSIA Growth benchmark',
        why_it_matters: 'Healthy mix prevents over-dependency on existing clients. Too high means poor retention.',
      },
      {
        name: 'Forecast Accuracy',
        description: 'Actual bookings as percentage of forecasted bookings.',
        unit: '%',
        benchmark_low: '<70%',
        benchmark_mid: '70-85%',
        benchmark_high: '>85%',
        source: 'CSO Insights',
        why_it_matters: 'Inaccurate forecasts cascade to hiring, capacity planning, and financial planning failures.',
      },
      {
        name: 'Quota Attainment',
        description: 'Percentage of reps achieving 100%+ of quota.',
        unit: '%',
        benchmark_low: '<40% of reps',
        benchmark_mid: '40-60%',
        benchmark_high: '>60% of reps',
        source: 'CSO Insights (median 53%)',
        why_it_matters: 'Low attainment signals quota setting, territory, or enablement issues. Also a retention risk.',
      },
      {
        name: 'Pipeline-to-Close Conversion (No Decision Rate)',
        description: 'Percentage of qualified pipeline that ends in "no decision."',
        unit: '%',
        benchmark_low: '>30% (too many stalls)',
        benchmark_mid: '15-30%',
        benchmark_high: '<15%',
        source: 'USDM FY2025 review (765 no-decisions worth $61.7M)',
        why_it_matters: 'No-decisions are wasted sales effort. High rate signals qualification or urgency creation problems.',
      },
      {
        name: 'Partner-Sourced Pipeline %',
        description: 'Percentage of pipeline originating from partner referrals/co-sell.',
        unit: '%',
        benchmark_low: '<10%',
        benchmark_mid: '10-25%',
        benchmark_high: '>25%',
        source: 'Forrester Partner Benchmark',
        why_it_matters: 'Partner-sourced deals often have higher win rates and lower CAC. Diversifies growth engine.',
      },
    ],
  },

  Marketing: {
    department_type: 'Marketing',
    intro: 'Marketing\'s job in PS is pipeline generation and brand positioning. These KPIs measure whether marketing is actually driving revenue, not just activity.',
    kpis: [
      {
        name: 'Marketing-Sourced Pipeline %',
        description: 'Percentage of total sales pipeline originated by marketing.',
        unit: '%',
        benchmark_low: '<10%',
        benchmark_mid: '10-25%',
        benchmark_high: '30-40%',
        source: 'Forrester B2B Marketing Benchmark. USDM FY2025: 5.8%',
        why_it_matters: 'The primary measure of marketing effectiveness. USDM at 5.8% vs 30-40% benchmark was the C- grade driver.',
      },
      {
        name: 'Cost per Marketing Qualified Lead (MQL)',
        description: 'Total marketing spend divided by MQLs generated.',
        unit: '$',
        benchmark_low: '>$500',
        benchmark_mid: '$200-$500',
        benchmark_high: '<$200',
        source: 'HubSpot B2B Benchmark (varies by industry)',
        why_it_matters: 'Efficiency measure. High CPL means marketing dollars are not working hard enough.',
      },
      {
        name: 'MQL-to-SQL Conversion Rate',
        description: 'Percentage of marketing qualified leads accepted by sales.',
        unit: '%',
        benchmark_low: '<10%',
        benchmark_mid: '10-25%',
        benchmark_high: '>25%',
        source: 'Gartner B2B benchmark',
        why_it_matters: 'Low conversion signals misalignment between marketing targeting and sales needs.',
      },
      {
        name: 'Website Traffic Growth (YoY)',
        description: 'Year-over-year growth in organic website visitors.',
        unit: '%',
        benchmark_low: '<5%',
        benchmark_mid: '5-20%',
        benchmark_high: '>20%',
        source: 'Industry average for B2B',
        why_it_matters: 'Organic growth indicates thought leadership and brand awareness. Reduces dependency on paid channels.',
      },
      {
        name: 'Event ROI',
        description: 'Pipeline generated per dollar spent on events.',
        unit: 'ratio',
        benchmark_low: '<2x',
        benchmark_mid: '2x-5x',
        benchmark_high: '>5x',
        source: 'USDM FY2025 review (events at 5.5x — a bright spot)',
        why_it_matters: 'Events are typically the largest marketing line item in PS. Must demonstrate clear pipeline return.',
      },
      {
        name: 'Content Engagement Rate',
        description: 'Average engagement (downloads, shares, time-on-page) per content piece.',
        unit: '%',
        benchmark_low: '<1%',
        benchmark_mid: '1-3%',
        benchmark_high: '>3%',
        source: 'Content Marketing Institute',
        why_it_matters: 'Measures content relevance. Low engagement means content doesn\'t resonate with target audience.',
      },
      {
        name: 'Paid Channel ROI',
        description: 'Pipeline or revenue generated per dollar of paid advertising.',
        unit: 'ratio',
        benchmark_low: '<1x (negative ROI)',
        benchmark_mid: '1x-3x',
        benchmark_high: '>3x',
        source: 'USDM FY2025 review (paid ads at $0 ROI)',
        why_it_matters: 'Paid channels must demonstrate positive ROI or spend should be reallocated.',
      },
      {
        name: 'Email List Health (Organic vs Purchased)',
        description: 'Percentage of email database that is organically grown vs purchased lists.',
        unit: '%',
        benchmark_low: '<30% organic',
        benchmark_mid: '30-70% organic',
        benchmark_high: '>70% organic',
        source: 'USDM FY2025 review (87% purchased ZoomInfo lists)',
        why_it_matters: 'Purchased lists have low engagement and high unsubscribe. Organic list indicates real brand interest.',
      },
    ],
  },

  IT: {
    department_type: 'IT',
    intro: 'IT enables every other department. These KPIs measure reliability, responsiveness, security, and cost-effectiveness of technology operations.',
    kpis: [
      {
        name: 'System Uptime / Availability',
        description: 'Percentage of time critical systems are available.',
        unit: '%',
        benchmark_low: '<99%',
        benchmark_mid: '99-99.9%',
        benchmark_high: '>99.9%',
        source: 'Gartner IT Operations',
        why_it_matters: 'Downtime directly impacts productivity across all departments. At USDM scale, 1% downtime = ~22 hours/year.',
      },
      {
        name: 'Mean Time to Resolve (MTTR)',
        description: 'Average time from incident reported to resolved.',
        unit: 'hours',
        benchmark_low: '>24 hours',
        benchmark_mid: '4-24 hours',
        benchmark_high: '<4 hours',
        source: 'HDI IT Support Benchmark',
        why_it_matters: 'Long resolution times compound productivity loss. Critical for billable staff who can\'t work during outages.',
      },
      {
        name: 'First Contact Resolution Rate',
        description: 'Percentage of support tickets resolved on first contact.',
        unit: '%',
        benchmark_low: '<50%',
        benchmark_mid: '50-70%',
        benchmark_high: '>70%',
        source: 'HDI (median 68%)',
        why_it_matters: 'Higher FCR = lower cost per ticket, faster user productivity restoration, better satisfaction.',
      },
      {
        name: 'IT Cost per Employee',
        description: 'Total IT spend divided by number of employees supported.',
        unit: '$',
        benchmark_low: '>$15K/employee',
        benchmark_mid: '$8K-$15K',
        benchmark_high: '<$8K',
        source: 'Gartner IT Key Metrics (PS industry)',
        why_it_matters: 'Measures IT efficiency. High cost per employee may signal over-spending or under-leveraging technology.',
      },
      {
        name: 'Security Incidents',
        description: 'Number of security incidents per quarter.',
        unit: 'count',
        benchmark_low: '>5/quarter',
        benchmark_mid: '1-5/quarter',
        benchmark_high: '0/quarter',
        source: 'Industry standard',
        why_it_matters: 'Life sciences clients require strong security posture. Incidents damage trust and can void contracts.',
      },
      {
        name: 'Patch Compliance Rate',
        description: 'Percentage of systems patched within SLA window.',
        unit: '%',
        benchmark_low: '<80%',
        benchmark_mid: '80-95%',
        benchmark_high: '>95%',
        source: 'CIS Benchmark',
        why_it_matters: 'Unpatched systems are the #1 attack vector. Critical for life sciences regulatory compliance.',
      },
      {
        name: 'Employee IT Satisfaction',
        description: 'Internal user satisfaction with IT services.',
        unit: 'score',
        benchmark_low: '<6 / 10',
        benchmark_mid: '6-8',
        benchmark_high: '>8 / 10',
        source: 'HDI Employee IT Survey benchmark',
        why_it_matters: 'Low satisfaction drives shadow IT adoption and reduces productivity. Leading indicator of IT effectiveness.',
      },
      {
        name: 'New Employee Provisioning Time',
        description: 'Time from hire approval to fully provisioned (email, tools, access).',
        unit: 'hours',
        benchmark_low: '>48 hours',
        benchmark_mid: '8-48 hours',
        benchmark_high: '<8 hours (day 1 ready)',
        source: 'Industry standard',
        why_it_matters: 'Slow provisioning means lost productivity for new hires and poor first impression. Especially costly for billable staff.',
      },
    ],
  },

  'HR Admin': {
    department_type: 'HR Admin',
    intro: 'HR\'s performance is measured by the health of the workforce it manages. These KPIs cover the full employee lifecycle from hiring through retention.',
    kpis: [
      {
        name: 'Voluntary Turnover Rate',
        description: 'Annual voluntary departures as percentage of headcount.',
        unit: '%',
        benchmark_low: '>20%',
        benchmark_mid: '12-20%',
        benchmark_high: '<12%',
        source: 'SHRM (PS industry median 15%)',
        why_it_matters: 'Every departure costs 50-200% of salary in replacement costs. Especially damaging for client-facing roles.',
      },
      {
        name: 'Time-to-Fill',
        description: 'Average days from job requisition to accepted offer.',
        unit: 'days',
        benchmark_low: '>60 days',
        benchmark_mid: '30-60 days',
        benchmark_high: '<30 days',
        source: 'SHRM (median 42 days)',
        why_it_matters: 'Open positions = lost revenue for billable roles and strain on remaining team for support roles.',
      },
      {
        name: 'Employee Engagement Score',
        description: 'Company-wide engagement survey result.',
        unit: 'score',
        benchmark_low: '<60%',
        benchmark_mid: '60-75%',
        benchmark_high: '>75%',
        source: 'Gallup (top quartile 73%+)',
        why_it_matters: 'Engaged employees are 21% more productive and 59% less likely to leave (Gallup).',
      },
      {
        name: 'Benefits Administration Accuracy',
        description: 'Percentage of benefits transactions processed without errors.',
        unit: '%',
        benchmark_low: '<95%',
        benchmark_mid: '95-99%',
        benchmark_high: '>99%',
        source: 'APQC Human Capital benchmark',
        why_it_matters: 'Benefits errors erode employee trust and create compliance risk.',
      },
      {
        name: 'Training Hours per Employee',
        description: 'Average annual training and development hours.',
        unit: 'hours',
        benchmark_low: '<10 hrs',
        benchmark_mid: '10-30 hrs',
        benchmark_high: '>30 hrs',
        source: 'ATD (Association for Talent Development) median 34 hrs',
        why_it_matters: 'Investment in development drives retention, skill currency, and service quality.',
      },
      {
        name: 'HR Cost per Employee',
        description: 'Total HR department cost divided by headcount served.',
        unit: '$',
        benchmark_low: '>$3,500',
        benchmark_mid: '$2,000-$3,500',
        benchmark_high: '<$2,000',
        source: 'APQC (median $2,986)',
        why_it_matters: 'Measures HR operational efficiency. Can be reduced through automation and self-service.',
      },
      {
        name: 'Onboarding Completion Rate (30-day)',
        description: 'Percentage of new hires completing all onboarding tasks within 30 days.',
        unit: '%',
        benchmark_low: '<70%',
        benchmark_mid: '70-90%',
        benchmark_high: '>90%',
        source: 'Industry standard',
        why_it_matters: 'Incomplete onboarding leads to slow ramp, compliance gaps, and early turnover.',
      },
      {
        name: 'Regrettable Turnover Rate',
        description: 'Departure rate of high-performing employees specifically.',
        unit: '%',
        benchmark_low: '>10%',
        benchmark_mid: '5-10%',
        benchmark_high: '<5%',
        source: 'SHRM',
        why_it_matters: 'Losing top talent is disproportionately damaging. This metric separates harmful turnover from healthy turnover.',
      },
    ],
  },

  Finance: {
    department_type: 'Finance',
    intro: 'Finance provides the financial intelligence and controls that enable good business decisions. These KPIs measure speed, accuracy, and strategic value.',
    kpis: [
      {
        name: 'Month-End Close Cycle Time',
        description: 'Business days from month-end to books closed.',
        unit: 'days',
        benchmark_low: '>15 days',
        benchmark_mid: '7-15 days',
        benchmark_high: '<7 days',
        source: 'APQC Finance Benchmark (top quartile 4.8 days)',
        why_it_matters: 'Faster close = faster decisions. USDM FY2025: Dec close was contaminated by closing entries.',
      },
      {
        name: 'Budget vs Actual Variance',
        description: 'Average absolute variance between budgeted and actual department spend.',
        unit: '%',
        benchmark_low: '>15%',
        benchmark_mid: '5-15%',
        benchmark_high: '<5%',
        source: 'APQC',
        why_it_matters: 'USDM FY2025 finding: No budget process exists. This is the foundational metric that was missing.',
      },
      {
        name: 'Forecast Accuracy',
        description: 'Revenue/expense forecast vs actual for the quarter.',
        unit: '%',
        benchmark_low: '<85%',
        benchmark_mid: '85-95%',
        benchmark_high: '>95%',
        source: 'APQC (top quartile >95%)',
        why_it_matters: 'Inaccurate forecasts cascade to bad hiring, spending, and investment decisions.',
      },
      {
        name: 'Days Sales Outstanding (DSO)',
        description: 'Average days to collect payment after invoicing.',
        unit: 'days',
        benchmark_low: '>60 days',
        benchmark_mid: '35-60 days',
        benchmark_high: '<35 days',
        source: 'APQC (PS median 48 days)',
        why_it_matters: 'High DSO ties up cash and may indicate billing/collection process issues.',
      },
      {
        name: 'Invoice Accuracy Rate',
        description: 'Percentage of invoices sent without errors requiring credit/rebill.',
        unit: '%',
        benchmark_low: '<95%',
        benchmark_mid: '95-99%',
        benchmark_high: '>99%',
        source: 'APQC',
        why_it_matters: 'Invoice errors damage client relationships, delay payment, and create rework.',
      },
      {
        name: 'Finance Cost as % of Revenue',
        description: 'Total finance department cost divided by company revenue.',
        unit: '%',
        benchmark_low: '>2%',
        benchmark_mid: '1-2%',
        benchmark_high: '<1%',
        source: 'APQC (median 1.3%)',
        why_it_matters: 'Measures finance operational efficiency. Automation should drive this down over time.',
      },
      {
        name: 'Audit Findings (Material)',
        description: 'Number of material findings in annual audit.',
        unit: 'count',
        benchmark_low: '>2',
        benchmark_mid: '1-2',
        benchmark_high: '0',
        source: 'Standard audit expectation',
        why_it_matters: 'Material findings indicate control failures. Zero is the target. USDM Dec closing entry issue was a warning.',
      },
      {
        name: 'AP Processing Cost per Invoice',
        description: 'Cost to process a single accounts payable invoice.',
        unit: '$',
        benchmark_low: '>$12',
        benchmark_mid: '$5-$12',
        benchmark_high: '<$5',
        source: 'APQC (top quartile $2.18)',
        why_it_matters: 'Automation benchmark. High processing cost signals manual AP workflows.',
      },
    ],
  },

  'Staffing/TA': {
    department_type: 'Staffing/TA',
    intro: 'Talent Acquisition is the front door of the company. These KPIs measure speed, quality, and cost of bringing talent into the organization.',
    kpis: [
      {
        name: 'Time-to-Fill',
        description: 'Average days from requisition open to offer accepted.',
        unit: 'days',
        benchmark_low: '>60 days',
        benchmark_mid: '30-60 days',
        benchmark_high: '<30 days',
        source: 'SHRM (median 42 days)',
        why_it_matters: 'For billable roles, every open day = lost revenue. For support roles, it means team strain.',
      },
      {
        name: 'Cost per Hire',
        description: 'Total recruiting cost (internal + external) per hire.',
        unit: '$',
        benchmark_low: '>$8,000',
        benchmark_mid: '$4,000-$8,000',
        benchmark_high: '<$4,000',
        source: 'SHRM (median $4,700)',
        why_it_matters: 'High cost per hire suggests over-reliance on agencies or inefficient sourcing.',
      },
      {
        name: 'Offer Acceptance Rate',
        description: 'Percentage of offers extended that are accepted.',
        unit: '%',
        benchmark_low: '<75%',
        benchmark_mid: '75-90%',
        benchmark_high: '>90%',
        source: 'SHRM',
        why_it_matters: 'Low acceptance rate wastes recruiting effort and signals comp, brand, or candidate experience issues.',
      },
      {
        name: 'Quality of Hire (90-Day Retention)',
        description: 'Percentage of new hires still employed after 90 days.',
        unit: '%',
        benchmark_low: '<85%',
        benchmark_mid: '85-95%',
        benchmark_high: '>95%',
        source: 'SHRM',
        why_it_matters: 'Early departures indicate screening failures. Each early departure costs the full cost-per-hire again.',
      },
      {
        name: 'Source Effectiveness (Internal vs Agency)',
        description: 'Percentage of hires from internal sourcing vs agency.',
        unit: '%',
        benchmark_low: '<60% internal',
        benchmark_mid: '60-80% internal',
        benchmark_high: '>80% internal',
        source: 'Industry standard',
        why_it_matters: 'Agency hires cost 3-5x internal sourcing. Higher internal ratio = lower cost and better culture fit.',
      },
      {
        name: 'Requisitions per Recruiter',
        description: 'Average open requisitions managed per recruiter.',
        unit: 'count',
        benchmark_low: '>25 (overloaded)',
        benchmark_mid: '15-25',
        benchmark_high: '<15',
        source: 'SHRM',
        why_it_matters: 'Overloaded recruiters provide poor candidate experience and slower fill times.',
      },
      {
        name: 'Hiring Manager Satisfaction',
        description: 'Internal satisfaction with recruiting service quality.',
        unit: 'score',
        benchmark_low: '<6 / 10',
        benchmark_mid: '6-8',
        benchmark_high: '>8 / 10',
        source: 'Industry standard',
        why_it_matters: 'Low hiring manager satisfaction often leads to managers bypassing TA, increasing risk and cost.',
      },
      {
        name: 'Candidate Experience Rating',
        description: 'Average candidate rating of the recruiting process.',
        unit: 'score',
        benchmark_low: '<6 / 10',
        benchmark_mid: '6-8',
        benchmark_high: '>8 / 10',
        source: 'Talent Board CandE benchmark',
        why_it_matters: 'Poor candidate experience damages employer brand. In life sciences, candidates talk to each other.',
      },
    ],
  },

  Quality: {
    department_type: 'Quality',
    intro: 'Quality & Compliance is a non-negotiable in life sciences. These KPIs measure regulatory readiness, process effectiveness, and risk management.',
    kpis: [
      {
        name: 'CAPA Close Rate (within SLA)',
        description: 'Percentage of CAPAs closed within target timeline.',
        unit: '%',
        benchmark_low: '<70%',
        benchmark_mid: '70-90%',
        benchmark_high: '>90%',
        source: 'Life sciences industry standard (30-day target)',
        why_it_matters: 'Open CAPAs signal unresolved quality issues. Regulators view aged CAPAs negatively.',
      },
      {
        name: 'Audit Finding Recurrence Rate',
        description: 'Percentage of audit findings that recur from prior audits.',
        unit: '%',
        benchmark_low: '>15%',
        benchmark_mid: '5-15%',
        benchmark_high: '<5%',
        source: 'Industry standard',
        why_it_matters: 'Recurring findings indicate ineffective root cause analysis and corrective actions.',
      },
      {
        name: 'Internal Audit Schedule Adherence',
        description: 'Percentage of planned internal audits completed on schedule.',
        unit: '%',
        benchmark_low: '<80%',
        benchmark_mid: '80-95%',
        benchmark_high: '>95%',
        source: 'ISO 9001 best practice',
        why_it_matters: 'Missed audits create compliance gaps and reduce inspection readiness.',
      },
      {
        name: 'Client Audit Pass Rate',
        description: 'Percentage of client audits passed without major findings.',
        unit: '%',
        benchmark_low: '<85%',
        benchmark_mid: '85-95%',
        benchmark_high: '>95%',
        source: 'Life sciences industry',
        why_it_matters: 'Failed client audits risk contract termination. Direct revenue impact.',
      },
      {
        name: 'SOP Currency Rate',
        description: 'Percentage of SOPs that are current (reviewed within cycle).',
        unit: '%',
        benchmark_low: '<80%',
        benchmark_mid: '80-95%',
        benchmark_high: '>95%',
        source: 'ISO 9001 / GxP standard',
        why_it_matters: 'Outdated SOPs create compliance risk and operational inconsistency.',
      },
      {
        name: 'Deviation Cycle Time',
        description: 'Average days from deviation reported to closed.',
        unit: 'days',
        benchmark_low: '>30 days',
        benchmark_mid: '15-30 days',
        benchmark_high: '<15 days',
        source: 'Life sciences industry standard',
        why_it_matters: 'Long deviation cycles indicate process inefficiency and risk of impact spreading.',
      },
      {
        name: 'Training Compliance Rate',
        description: 'Percentage of required training completed on time.',
        unit: '%',
        benchmark_low: '<85%',
        benchmark_mid: '85-95%',
        benchmark_high: '>95%',
        source: 'GxP requirement',
        why_it_matters: 'Incomplete training is a top regulatory citation. Non-negotiable in life sciences.',
      },
    ],
  },

  RMO: {
    department_type: 'RMO',
    intro: 'The Resource Management Office optimizes the most expensive asset: people. These KPIs measure how effectively resources are matched to demand.',
    kpis: [
      {
        name: 'Resource Request Fulfillment Time',
        description: 'Average days from staffing request to resource assigned.',
        unit: 'days',
        benchmark_low: '>15 days',
        benchmark_mid: '5-15 days',
        benchmark_high: '<5 days',
        source: 'SPI Research',
        why_it_matters: 'Slow fulfillment = project delays, client dissatisfaction, and potential revenue leakage.',
      },
      {
        name: 'Fulfillment Rate',
        description: 'Percentage of resource requests fulfilled from internal pool (vs external hire/contractor).',
        unit: '%',
        benchmark_low: '<60%',
        benchmark_mid: '60-80%',
        benchmark_high: '>80%',
        source: 'Industry standard',
        why_it_matters: 'High internal fulfillment indicates good demand forecasting and workforce planning.',
      },
      {
        name: 'Skills Match Accuracy',
        description: 'Percentage of placements where resource skills fully match requirements.',
        unit: '%',
        benchmark_low: '<70%',
        benchmark_mid: '70-85%',
        benchmark_high: '>85%',
        source: 'Industry standard',
        why_it_matters: 'Poor matches lead to ramp time, rework, and client dissatisfaction.',
      },
      {
        name: 'Demand Forecast Accuracy (30-day)',
        description: 'Accuracy of resource demand predictions 30 days out.',
        unit: '%',
        benchmark_low: '<60%',
        benchmark_mid: '60-80%',
        benchmark_high: '>80%',
        source: 'SPI Research',
        why_it_matters: 'Good forecasting enables proactive hiring and reduces bench time.',
      },
      {
        name: 'Average Bench Days',
        description: 'Average days consultants spend unassigned between engagements.',
        unit: 'days',
        benchmark_low: '>20 days',
        benchmark_mid: '10-20 days',
        benchmark_high: '<10 days',
        source: 'SPI Research',
        why_it_matters: 'Bench time is direct cost with zero revenue. RMO exists to minimize this.',
      },
      {
        name: 'Stakeholder Satisfaction (Delivery Managers)',
        description: 'Satisfaction of delivery/project managers with RMO service.',
        unit: 'score',
        benchmark_low: '<6 / 10',
        benchmark_mid: '6-8',
        benchmark_high: '>8 / 10',
        source: 'Internal benchmark',
        why_it_matters: 'If PMs don\'t trust RMO, they hoard resources or recruit independently, defeating the purpose.',
      },
    ],
  },
}

export function getDeptKPIs(departmentType: string): DeptKPISet | undefined {
  return DEPT_KPIS[departmentType]
}
